# Change these first
owner: Weoja # Your GitHub organization or username, where this repository lives
repo: weoja-status # The name of this repository

sites:
  - name: Weoja Search
    url: https://weoja.com
  - name: Weoja API VN
    url: https://api.weoja.com
  - name: Weoja API VN 2
    url: https://api-vn2.weoja.com
  - name: Weoja API DE
    url: https://api-de.weoja.com
  - name: Weoja API IN
    url: https://api-in.weoja.com
  - name: Weoja API SG
    url: https://api-sg.weoja.com
  - name: Weoja API US
    url: https://api-us.weoja.com
  - name: Weoja Map
    url: https://map.weoja.com
  - name: Weoja API VN
    url: https://api.weoja.com
  - name: Weoja Accounts
    url: https://accounts.weoja.dev
    expectedStatusCodes:
      - 404
  - name: Weoja Services
    url: https://ip-details.weoja.dev/
    expectedStatusCodes:
      - 404
  - name: Weoja Job
    url: https://job.weoja.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.weoja.dev
  # baseUrl: /your-repo-name
  logoUrl: https://assets.weoja.com/logo.svg
  faviconSvg: https://assets.weoja.com/logo.svg
  name: Weoja Status
  introTitle: "**Weoja Status**"
  introMessage: Status of Weoja Services
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
      # href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
