# Change these first
owner: Weoja # Your GitHub organization or username, where this repository lives
repo: weoja-status # The name of this repository

sites:
  - name: Weoja Search
    url: https://weoja.com
  - name: Weoja API VN
    url: https://api.weoja.com/v1/health
  - name: Weoja API DE
    url: https://api-de.weoja.com/v1/health
  - name: Weoja API IN
    url: https://api-in.weoja.com/v1/health
  - name: Weoja API SG
    url: https://api-sg.weoja.com/v1/health
  - name: Weoja API US
    url: https://api-us.weoja.com/v1/health
  - name: Weoja API JP
    url: https://api-jp.weoja.com/v1/health
  - name: Weoja API CN
    url: https://api-cn.weoja.com/v1/health
  - name: Weoja API UK
    url: https://api-uk.weoja.com/v1/health
  - name: Weoja API FR
    url: https://api-fr.weoja.com/v1/health
  - name: Weoja API NL
    url: https://api-nl.weoja.com/v1/health
  - name: Weoja API CA
    url: https://api-ca.weoja.com/v1/health
  - name: Weoja API KR
    url: https://api-kr.weoja.com/v1/health
  - name: Weoja Map
    url: https://map.weoja.com
  - name: Weoja Accounts
    url: https://accounts.weoja.dev
  - name: Weoja Services
    url: https://ip-details.weoja.dev/
    expectedStatusCodes:
      - 400
  - name: Weoja Job
    url: https://job.weoja.dev
  - name: Weoja Bot
    url: https://bot.weoja.com
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.weoja.dev
  # baseUrl: /your-repo-name
  logoUrl: https://assets.weoja.com/logo.svg
  faviconSvg: https://assets.weoja.com/logo.svg
  name: Weo | Status
  introTitle: "**Weo | Status**"
  introMessage: Status of Weo Services
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
      # href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
